"""create question collection table

Revision ID: 514b301c8bdf
Revises: 790095308492
Create Date: 2023-01-31 13:31:16.286453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514b301c8bdf'
down_revision = '790095308492'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_collections',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'collection_id')
    )
    op.create_index(op.f('ix_question_collections_collection_id'), 'question_collections', ['collection_id'], unique=False)
    op.create_index(op.f('ix_question_collections_question_id'), 'question_collections', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_collections_question_id'), table_name='question_collections')
    op.drop_index(op.f('ix_question_collections_collection_id'), table_name='question_collections')
    op.drop_table('question_collections')
    # ### end Alembic commands ###
